version: '3.8'

services:
  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcp-server
    restart: unless-stopped
    # Since MCP server uses stdio transport, we don't need to expose ports
    # but we can mount a workspace directory for file operations
    volumes:
      - ./workspace:/app/workspace:ro  # Mount workspace as read-only for security
      - /tmp:/tmp:rw  # Allow access to temp directory if needed
    environment:
      - NODE_ENV=production
    # Override the default command to specify a base path
    command: ["node", "dist/index.js", "--path", "/app/workspace"]
    # Health check
    healthcheck:
      test: ["CMD", "node", "-e", "console.log('Health check passed')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Development service with live reload
  mcp-server-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: mcp-server-dev
    volumes:
      - .:/app
      - /app/node_modules
      - ./workspace:/app/workspace:ro
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "dev"]
    profiles:
      - dev

# Optional: Add a network for future services
networks:
  default:
    name: mcp-network
