services:
  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcp-server
    restart: "no"  # Don't restart automatically since it's a stdio server
    stdin_open: true  # Keep stdin open for stdio communication
    tty: true  # Allocate a pseudo-TTY
    # Since MCP server uses stdio transport, we don't need to expose ports
    # but we can mount a workspace directory for file operations
    volumes:
      - ./workspace:/app/workspace:ro  # Mount workspace as read-only for security
      - /tmp:/tmp:rw  # Allow access to temp directory if needed
    environment:
      - NODE_ENV=production
    # Override the default command to specify a base path
    command: ["dumb-init", "node", "dist/index.js", "--path", "/app/workspace"]
    # Remove health check since stdio servers don't work well with health checks

  # Development service with live reload
  mcp-server-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: mcp-server-dev
    stdin_open: true
    tty: true
    volumes:
      - .:/app
      - /app/node_modules
      - ./workspace:/app/workspace:ro
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "dev"]
    profiles:
      - dev

# Optional: Add a network for future services
networks:
  default:
    name: mcp-network
